version: '2.1'

services:
  noxbot:
    image: noxbot
    environment:
      NODE_ENV: swarm
    build:
      context: "."
    ports:
      - 3000:3000
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  redis:
    image: "redis"
    ports:
      - 6379:6379